#!/usr/bin/python
# cat unique_count  | ./unique_count

import fileinput
import operator

seen = dict()

for line in fileinput.input():
   line = line.rstrip('\n'); 
   if (line in seen):
      seen[line] += 1
   else:
      seen[line] = 1

for key in seen.keys():
   print (str(seen[key]) + " : " + key)
